# Generated by Django 5.0.1 on 2024-01-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cnes', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.IntegerField(default=5)),
                ('data', models.DateField()),
                ('horas', models.CharField(choices=[('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='candidato.candidato')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.estabelecimento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('data', 'horas'), name='data_hora'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.horario'),
        ),
    ]
