# Generated by Django 5.0.1 on 2024-01-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
