# Generated by Django 5.0.1 on 2024-01-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_alter_agendamento_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estabelecimento',
            name='cnes',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
