# Generated by Django 5.0.1 on 2024-01-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('data_nascimento', models.DateField()),
                ('covid', models.BooleanField(default=False)),
                ('senha', models.CharField(max_length=255)),
                ('grupo_atendimento', models.ManyToManyField(blank=True, to='candidato.grupoatendimento')),
            ],
        ),
    ]
